from flask_sqlalchemy import SQLAlchemy
db = SQLAlchemy()

class Entrada(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    emitente = db.Column(db.String(40), nullable=False)
    classificação = db.Column(db.String(15), nullable=False)
    empresa = db.Column(db.String(15), nullable=False)
    data = db.Column(db.Date, nullable=False)
    hora = db.Column(db.Time, nullable=False)
    local = db.Column(db.String(20), nullable=False)
    observação = db.Column(db.String(150), nullable=False)
    ação = db.Column(db.String(150), nullable=False)
    class_sst = db.Column(db.String(300), nullable=True)
    class_ambiental = db.Column(db.String(300), nullable=True)
    causa = db.Column(db.String(300), nullable=True)
    parecer = db.Column(db.String(100), nullable=True)
    num_ordem_man = db.Column(db.String(20), nullable=True)
    obs_sprocedencia = db.Column(db.String(20), nullable=True)
    obs_justificativa = db.Column(db.String(20), nullable=True)
    multipla_condição = db.Column(db.String(60), nullable=True)
    multipla_comportamento = db.Column(db.String(60), nullable=True)
    multipla_ambiental = db.Column(db.String(60), nullable=True)
    verificação = db.Column(db.String(20), nullable=True)